package main

import (
	"context"
	_ "embed"
	"fmt"
	"log"

	_ "github.com/mattn/go-sqlite3"

	"github.com/tetratelabs/wazero"
	"github.com/tetratelabs/wazero/imports/wasi_snapshot_preview1"
)

// sqlWasm was generated by the following:
//
//	cd testdata; tinygo build -o sql_example.wasm -target=wasi sql_example.go
//
//go:embed testdata/sql_example.wasm
var sqlWasm []byte

// main demonstrates using the wasi:sql API from a WebAssembly guest application.
//
// The guest application (compiled from sql_example.go with TinyGo) performs:
//   - Opens a SQLite in-memory database connection
//   - Creates a 'users' table
//   - Inserts a row
//   - Queries the table
//
// This example shows how WebAssembly modules can interact with SQL databases
// through the wasi:sql@0.2.0-draft API implementation in wazero.
func main() {
	ctx := context.Background()

	// Create a new WebAssembly Runtime.
	r := wazero.NewRuntime(ctx)
	defer r.Close(ctx)

	// Instantiate WASI, which includes the SQL functions.
	wasi_snapshot_preview1.MustInstantiate(ctx, r)

	// Instantiate the guest Wasm module.
	config := wazero.NewModuleConfig().
		WithStdout(nil).
		WithStderr(nil).
		WithStartFunctions("_start") // TinyGo uses _start

	mod, err := r.InstantiateWithConfig(ctx, sqlWasm, config)
	if err != nil {
		log.Fatalf("failed to instantiate module: %v", err)
	}
	defer mod.Close(ctx)

	fmt.Println("\nWebAssembly SQL example completed successfully!")
}
